version: '2'
services:
  chris-test:
    container_name: chris-test
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www/html
    entrypoint: ["php", "runner.php"]
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    logging:
      driver: none
